# 画面回りの設定値
display:
  width: 320
  height: 280
  tile_x: 16
  tile_y: 14
  tile_size: 20
  background: [135, 206, 235]         # RGB 水色

# ゲーム周りの設定値
game:
  frame_rate: 30                      # フレームレート(1秒間に30フレーム)
  hatena_interval: 200                # ？ブロック切替間隔
  coin_interval: 5                    # コイン切替間隔
  invincibility_duration: 3000        # 無敵状態の継続時間
  gravity: 1                          # ゲーム内での重力値
  walk_speed: 5                       # 歩行速度
  jump_speed: -10                     # ジャンプ速度
  shell_speed: 5                      # 甲羅速度
  dead_jump_height: -12               # 死亡時に飛び上がる高さ
  dead_anime_counter: 12              # 死亡時のカウンター上限値
  disappear_delay: 15                 # 踏まれた後消えるまでの時間（フレーム数）
  stomped_timer: 15                   # 踏まれてから次のアクションへ移行するまでの猶予時間
  safe_timer: 15                      # キックしてから次のアクションへ移行するまでの猶予時間
  appear_distance: 20                 # アイテムがブロックから上に出現する幅

# ブロック周りの設定値
block:
  types:
    ground: 1                         # 地面
    wall: 2                           # 壁
    block: 3                          # ブロック(破壊可能)
    released: 4                       # アイテム放出済
    hatena_kinoko: 5                  # ？ブロック(キノコ)
    hatena_coin: 6                    # ？ブロック(コイン)

  block_fragments:                    # ブロックの破片
    horizontal_speed_range: [-3, 3]   # 水平方向の速度範囲
    vertical_speed_range: [-8, -5]    # 垂直方向の速度範囲
